### ISSUE TITLE
Example app?

### ISSUE THREAD

**Issue by DanCouper** [opendrops/passport#1]
Any chance of filling out the example, I like the simplicity of what you've got so far here, but I'm having trouble getting it functional - seeing how you've done it would help a lot.

**Comment by shankardevy** [comment]
@DanCouper I will have one ready within a day. thanks for your interest.

**Comment by shankardevy** [comment]
@DanCouper pull the latest code from this repo
example_app folder in the repo contains a working version of a phoenix app with password.

You need to do the following to get it working
```
cd example_app
mix do deps.get, compile # get the dependencies and  compile
mix ecto.create # create a postgres database
mix ecto.migrate # Run ecto migrations. basically create users table.
npm install # install the node dependencies. 
mix phoenix.server # You should be able to see the site now in localhost:4000 . 
```
All that being said, this package is still experimental and there is still a lot to do to make it production ready.
