### ISSUE TITLE
Get the current user in controller

### ISSUE THREAD

**Issue by Anonyfox** [opendrops/passport#10]
I have a phoenix collection which has a relation `:belongs_to :user`. When creating a new record, I want to get the current user's ID inside the `create` action of my controller, and modify the changeset accordingly. 

How do I get the current User's ID? Passport itself seems to work fine, with registration and so on. Any ideas?

**Comment by Anonyfox** [comment]
Okay, seems that `import Passport.SessionManager, only: [:current_user/1]` and then in the action `Passport.SessionManager.current_user(conn)` does the trick. 

Is there any trick how I can register the current_user/1 function globally in my phoenix app?

**Comment by arthurcolle** [comment]
@Anonyfox: Like in your controllers as well?

**Comment by Anonyfox** [comment]
Controllers, Views, Models, everywhere I might need the current_user. For example some View method that does something dependent on the current_user or sth else, and so on

**Comment by shankardevy** [comment]
I haven't committed myself to this project for sometime. But I am available now. Sorry guys for not being so helpful in the past few months. 

@Anonyfox `current_user(@conn)` should give you the current user and it should work in both templates and controllers. btw, I have updated Passport to work with latest Phoenix and Ecto. Give it a try.

**Comment by Anonyfox** [comment]
Welcome back, and nice to hear from you!

**Comment by fmounir** [comment]
@Anonyfox  your solution seems to be not working in the current version , can you tell me how to get the current_user in the controller , @shankardevy  please help :)

**Comment by tronathan** [comment]
Not sure if this will help anyone track it down, but `current_user` appears to be defined here:

https://github.com/opendrops/passport/blob/608b6f1e7eee00e5a92c38fd6dafaa3d41900fbf/lib/passport/plug.ex#L7

**Comment by tronathan** [comment]
It appears that you can use the following line to get the current user id in a controller without any additional imports:

```
get_session(conn, :user_id)
```

To find this out, I looked at the implementation of `current_user` from the link above and tried putting

```
IO.inspect get_session(conn, :user_id)
```

into my controller.  Looking at the logs, I see the user id.

**Comment by fmounir** [comment]
Thanks buddy :) will try it :)
