### ISSUE TITLE
Hex dependency resolution failed

### ISSUE THREAD

**Issue by dayvsonsales** [opendrops/passport#17]
Trying to add passport in my test project, but I get error message:

```
Looking up alternatives for conflicting requirements on phoenix_ecto
  Activated version: 1.2.0
  From mix.exs: ~> 1.1
  From mix.lock: 1.2.0
  From passport v0.0.3: ~> 0.2

** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies
```

**Comment by acconrad** [comment]
I had the same issue and I resolved it by changing the passport line in `mix.exs` to depend on the actual github project, which I think is more up-to-date than the mix repo:

```elixir
{:passport, "~> 0.0.3", github: "opendrops/passport", override: true}
```

**Comment by dayvsonsales** [comment]
Thanks for your answer. But I think this repository is abandoned =/, now I'm using another auth module.

**Comment by acconrad** [comment]
@dayvsonsales which one are you using? Addict?

**Comment by dayvsonsales** [comment]
@acconrad Yes.

**Comment by b-murphy** [comment]
+1

**Comment by shankardevy** [comment]
fixed in master
