### ISSUE TITLE
Redo Passport ground up

### ISSUE THREAD

**Issue by shankardevy** [opendrops/passport#20]
Passport should care only about one thing: authentication. Existing libraries try to do more than that which is imposing a few limitations in some of the projects I work with. I plan to do a complete authentication framework for Phoenix using Passport.  `Passport` will be accompanied by `Visa` that can allow multiple roles per user. This issue is to track to many related ones that I consider as important before releasing a stable v1.

**Comment by collegeimprovements** [comment]
This looks awesome. Let me know if I can help you somehow.

**Comment by toraritte** [comment]
I think this is a wonderful module in its simplicity: it does one thing but it does it well. Too bad that it's that well hidden among the "big" ones (coherence, guardian, addict). I agree with you that other libraries are bloated and it is hard to sort out the things you need.

Do you have any roadmap for the future?

Thanks again!

**Comment by shankardevy** [comment]
@toraritte I have rewritten Passport for Phoenix 1.3. Please check the latest master. Roadmap will be on issue queue shortly.

**Comment by toraritte** [comment]
I'm sorry I missed your comment. Hopefully I'll get to the authentication part of our project and I can give you some feedback on how it went. I just saw your also published a couple of guides, looking forward to read them!
