### ISSUE TITLE
Where's the plug that protects pages and redirects them to the login page

### ISSUE THREAD

**Issue by smpallen99** [opendrops/passport#23]
Am I missing something here? How to we force authentication on protected pages?

**Comment by jespr** [comment]
@smpallen99 You can do something along the lines of

```elixir
defmodule MyProject.AuthenticatedController do
  use MyProject.Web, :controller
  plug :authenticate

  def index(conn, _) do
    render(conn, "index.html")
  end

  defp authenticate(conn, _) do
     case get_session(conn, :user_id) do
        nil ->
           conn |> put_flash(:info, "You must be signed in") |> redirect(to: "/") |> halt
        _ ->
           conn
     end
  end
end
```

**Comment by bagilevi** [comment]
You can add this to `web/router.ex`:

        # unauthenticated routes go here

        scope "/" do
          pipe_through :authenticate

          # routes that require login go here
        end

Made a pull request to add this to the readme: #31
