### ISSUE TITLE
Please adjust the dependencies to work with Phoenix 1.2

### ISSUE THREAD

**Issue by acrolink** [opendrops/passport#26]

**Comment by wmeints** [comment]
Running into problems here as well.

**Comment by acrolink** [comment]
@wmeints You can use my adjusted branch at https://github.com/acrolink/passport inside your project's mix.exs file (as source for passport dependency), I have resolved the dependency issues inside my branch.

**Comment by shankardevy** [comment]
fixed on master. thanks
