### ISSUE TITLE
Version on Hex out of date

### ISSUE THREAD

**Issue by yoshikischmitz** [opendrops/passport#3]
The version on Hex right now is missing `Passport.AuthenticationPlug`. Maybe bump versions and republish?

**Comment by shankardevy** [comment]
just updated. you should now be able to use the version '0.0.3' now. Following the readme should now work but still have to update the example app included in this repo. I will keep this issue open until I update the example project.

thanks for your interest.

**Comment by yoshikischmitz** [comment]
:+1:
