### ISSUE TITLE
Fix Build Badge: Currently Unknown

### ISSUE THREAD

**Issue by cloudbring** [opendrops/passport#5]
[![Build Status](https://travis-ci.org/opendrops/passport.svg?branch=master)](https://travis-ci.org/opendrops/passport)

Currently that's unknown. It should say either pass or fail. I'd be interested in investigating it eventually if no one else has the time to setup up.

**Comment by shankardevy** [comment]
I have no idea yet. But I guess it is because there are now no test cases actually running. Some of the previously added test code were not really useful and hence removed. If you can write some test, it's most welcome.

**Comment by shankardevy** [comment]
Passport has gone a full rewrite for Phoenix 1.3. Will add the test badge shortly.
